# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.digitalkin.service.v1.trigger import trigger_service_pb2 as digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2


class TriggerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrigger = channel.stream_stream(
                '/digitalkin.service.v1.trigger.TriggerService/StartTrigger',
                request_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StartTriggerRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.FromString,
                )
        self.StopTrigger = channel.unary_unary(
                '/digitalkin.service.v1.trigger.TriggerService/StopTrigger',
                request_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StopTriggerRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.FromString,
                )
        self.GetTriggerStatus = channel.unary_unary(
                '/digitalkin.service.v1.trigger.TriggerService/GetTriggerStatus',
                request_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerStatusRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerStatusResponse.FromString,
                )
        self.GetTriggerInput = channel.unary_unary(
                '/digitalkin.service.v1.trigger.TriggerService/GetTriggerInput',
                request_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerInputRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerInputResponse.FromString,
                )
        self.GetTriggerOutput = channel.unary_unary(
                '/digitalkin.service.v1.trigger.TriggerService/GetTriggerOutput',
                request_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerOutputRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerOutputResponse.FromString,
                )


class TriggerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTrigger(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggerInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggerOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TriggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrigger': grpc.stream_stream_rpc_method_handler(
                    servicer.StartTrigger,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StartTriggerRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.SerializeToString,
            ),
            'StopTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTrigger,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StopTriggerRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.SerializeToString,
            ),
            'GetTriggerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggerStatus,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerStatusRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerStatusResponse.SerializeToString,
            ),
            'GetTriggerInput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggerInput,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerInputRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerInputResponse.SerializeToString,
            ),
            'GetTriggerOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggerOutput,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerOutputRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.service.v1.trigger.TriggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TriggerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTrigger(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/digitalkin.service.v1.trigger.TriggerService/StartTrigger',
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StartTriggerRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.trigger.TriggerService/StopTrigger',
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.StopTriggerRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTriggerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.trigger.TriggerService/GetTriggerStatus',
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerStatusRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTriggerInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.trigger.TriggerService/GetTriggerInput',
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerInputRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerInputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTriggerOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.trigger.TriggerService/GetTriggerOutput',
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.GetTriggerOutputRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_trigger_dot_trigger__service__pb2.TriggerOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
