# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/service/v1/chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n digitalkin/service/v1/chat.proto\x12\x15\x64igitalkin.service.v1\"X\n\x0b\x43hatMessage\x12\x1b\n\tuser_name\x18\x01 \x01(\tR\x08userName\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x12\n\x04room\x18\x03 \x01(\tR\x04room2g\n\x0b\x43hatService\x12X\n\x08JoinChat\x12\".digitalkin.service.v1.ChatMessage\x1a\".digitalkin.service.v1.ChatMessage\"\x00(\x01\x30\x01\x42\x9e\x01\n\x19\x63om.digitalkin.service.v1B\tChatProtoH\x02P\x01\xa2\x02\x03\x44SX\xaa\x02\x15\x44igitalkin.Service.V1\xca\x02\x15\x44igitalkin\\Service\\V1\xe2\x02!Digitalkin\\Service\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Service::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.service.v1.chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.digitalkin.service.v1B\tChatProtoH\002P\001\242\002\003DSX\252\002\025Digitalkin.Service.V1\312\002\025Digitalkin\\Service\\V1\342\002!Digitalkin\\Service\\V1\\GPBMetadata\352\002\027Digitalkin::Service::V1'
  _CHATMESSAGE._serialized_start=59
  _CHATMESSAGE._serialized_end=147
  _CHATSERVICE._serialized_start=149
  _CHATSERVICE._serialized_end=252
# @@protoc_insertion_point(module_scope)
