# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.digitalkin.service.v1 import chat_pb2 as digitalkin_dot_service_dot_v1_dot_chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinChat = channel.stream_stream(
                '/digitalkin.service.v1.ChatService/JoinChat',
                request_serializer=digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinChat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinChat': grpc.stream_stream_rpc_method_handler(
                    servicer.JoinChat,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.service.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/digitalkin.service.v1.ChatService/JoinChat',
            digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_chat__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
