# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.digitalkin.service.v1 import service_pb2 as digitalkin_dot_service_dot_v1_dot_service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartService = channel.stream_stream(
                '/digitalkin.service.v1.Service/StartService',
                request_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceResponse.FromString,
                )
        self.StopService = channel.unary_unary(
                '/digitalkin.service.v1.Service/StopService',
                request_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StopServiceRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceResponse.FromString,
                )
        self.GetServiceStatus = channel.unary_unary(
                '/digitalkin.service.v1.Service/GetServiceStatus',
                request_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceStatusRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceStatusResponse.FromString,
                )
        self.GetServiceInput = channel.unary_unary(
                '/digitalkin.service.v1.Service/GetServiceInput',
                request_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceInputRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceInputResponse.FromString,
                )
        self.GetServiceOutput = channel.unary_unary(
                '/digitalkin.service.v1.Service/GetServiceOutput',
                request_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceOutputRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceOutputResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartService(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceOutput(self, request, context):
        """rpc GetServiceSetup (GetServiceSetupRequest) returns (ServiceSetupResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartService': grpc.stream_stream_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceResponse.SerializeToString,
            ),
            'StopService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.StopServiceRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceStatusRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceStatusResponse.SerializeToString,
            ),
            'GetServiceInput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInput,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceInputRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceInputResponse.SerializeToString,
            ),
            'GetServiceOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceOutput,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceOutputRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.service.v1.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/digitalkin.service.v1.Service/StartService',
            digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_service__pb2.StartServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.Service/StopService',
            digitalkin_dot_service_dot_v1_dot_service__pb2.StopServiceRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.Service/GetServiceStatus',
            digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceStatusRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.Service/GetServiceInput',
            digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceInputRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceInputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.Service/GetServiceOutput',
            digitalkin_dot_service_dot_v1_dot_service__pb2.GetServiceOutputRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_service__pb2.ServiceOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
