# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.digitalkin.service.v1.registry import service_registry_pb2 as digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2


class ServiceRegistryStub(object):
    """Service definition for the Service Registry
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterService = channel.unary_unary(
                '/digitalkin.service.v1.registry.ServiceRegistry/RegisterService',
                request_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterResponse.FromString,
                )
        self.DeregisterService = channel.unary_unary(
                '/digitalkin.service.v1.registry.ServiceRegistry/DeregisterService',
                request_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterResponse.FromString,
                )
        self.DiscoverService = channel.unary_unary(
                '/digitalkin.service.v1.registry.ServiceRegistry/DiscoverService',
                request_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverResponse.FromString,
                )
        self.UpdateServiceStatus = channel.unary_unary(
                '/digitalkin.service.v1.registry.ServiceRegistry/UpdateServiceStatus',
                request_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusResponse.FromString,
                )


class ServiceRegistryServicer(object):
    """Service definition for the Service Registry
    """

    def RegisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterResponse.SerializeToString,
            ),
            'DeregisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterService,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterResponse.SerializeToString,
            ),
            'DiscoverService': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverService,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverResponse.SerializeToString,
            ),
            'UpdateServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceStatus,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.service.v1.registry.ServiceRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceRegistry(object):
    """Service definition for the Service Registry
    """

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.registry.ServiceRegistry/RegisterService',
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeregisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.registry.ServiceRegistry/DeregisterService',
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DeregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.registry.ServiceRegistry/DiscoverService',
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.DiscoverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.registry.ServiceRegistry/UpdateServiceStatus',
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_registry_dot_service__registry__pb2.UpdateStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
