import datetime
import time
from typing import Any, Dict, List, Callable


class Node:
    """
    Represents a node in the graph.

    Attributes:
        node_id (str): The unique identifier of the node.
        node_type (str): The type of the node.
        inputs (List[Dict[str, Any]]): The inputs of the node.
        outputs (List[Dict[str, Any]]): The outputs of the node.
        status (str): The status of the node execution.
        current_execution (int): The current execution count.
        last_execution (datetime.datetime): The timestamp of the last execution.
        lock (threading.Lock): A lock to ensure thread safety during execution.
    """

    def __init__(
        self,
        node_id: str,
        node_type: str,
        service_type: str,
        service_id: str,
        inputs: List[Dict[str, Any]],
        outputs: List[Dict[str, Any]],
        setup: Dict[str, Any],
    ):
        # value
        self.node_id = node_id
        self.node_type = node_type
        self.service_type = service_type
        self.service_id = service_id
        self.inputs = inputs
        self.outputs = outputs
        self.status = "pending"  # 'pending', 'running', 'completed', 'failed'
        self.current_execution = 0
        self.last_execution = None
        self.setup = setup

    async def execute(
        self, input_data: Dict[str, Any], service_callback: Callable
    ) -> Dict[str, Any]:
        """
        Executes the node with the given input data.

        Args:
            input_data (Dict[str, Any]): The input data for the node.

        Returns:
            Dict[str, Any]: The output data generated by the node.
        """
        self.status = "running"
        print(f"Executing node {self.service_type}:{self.node_id}")
        await service_callback(self.service_id)
        time.sleep(5)  # Simulate some work being done
        output_data = {
            output["label"]: f"output_of_{output['label']}_{self.node_id}"
            for output in self.outputs
        }
        print(output_data)
        self.outputs = [
            {
                **output,
                "value": f"output_of_{output['label']}_{self.node_id}",
                "updated_at": datetime.datetime.now(),
            }
            for output in self.outputs
        ]
        self.status = "completed"
        return output_data

    async def get_setup(self, setup_id: str) -> Dict[str, Any]:
        """
        Get the setup data for the given setup id.

        Args:
            setup_id (str): The unique identifier of the setup.

        Returns:
            Dict[str, Any]: The setup data.
        """
        return {
            "setup_id": setup_id,
            "setup_data": f"setup_data_{setup_id}",
        }
