import datetime
import time
from typing import Any, Dict, List, Callable, Optional

from pydantic import BaseModel, Field

from kin_sdk.common.types import ServiceType


class InputData(BaseModel):
    label: Optional[str] = Field(None, description="input label")
    value: Optional[Any] = Field(None, description="input value")
    updated_at: Optional[datetime.datetime] = Field(
        None, description="input updated at"
    )
    optional: bool = Field(False, description="input optional")


class OutputData(BaseModel):
    label: Optional[str] = Field(None, description="output label")
    value: Optional[Any] = Field(None, description="output value")
    updated_at: Optional[datetime.datetime] = Field(
        None, description="output updated at"
    )
    optional: bool = Field(False, description="output optional")


class Node:
    """
    Represents a node in the graph.

    Attributes:
        node_id (str): The unique identifier of the node.
        node_type (str): The type of the node.
        inputs (List[Dict[str, Any]]): The inputs of the node.
        outputs (List[Dict[str, Any]]): The outputs of the node.
        status (str): The status of the node execution.
        current_execution (int): The current execution count.
        last_execution (datetime.datetime): The timestamp of the last execution.
        lock (threading.Lock): A lock to ensure thread safety during execution.
    """

    def __init__(
        self,
        node_id: str,
        node_type: str,
        service_type: ServiceType,
        service_id: str,
        inputs: List[Dict[str, Any]],
        outputs: List[Dict[str, Any]],
        setup: Dict[str, Any],
    ):
        # value
        self.node_id = node_id
        self.node_type = node_type
        self.service_type = service_type
        self.service_id = service_id
        self.inputs = [InputData(**input) for input in inputs]
        self.outputs = [OutputData(**output) for output in outputs]
        self.status = "pending"  # 'pending', 'running', 'completed', 'failed'
        self.current_execution = 0
        self.last_execution = None
        self.setup = setup

    @property
    def values(self) -> Dict[str, Any]:
        inputs = {}
        for input in self.inputs:
            print(f"\t\t- input: {input}")
            if input.label is not None:
                inputs[input.label] = input.value
        return inputs

    async def execute(self, service_callback: Callable) -> Dict[str, OutputData]:
        """
        Executes the node with the given input data.

        Args:
            input_data (Dict[str, Any]): The input data for the node.

        Returns:
            Dict[str, Any]: The output data generated by the node.
        """
        try:
            self.status = "running"
            print(f"Executing node {self.service_type}:{self.node_id}")
            service_response = await service_callback(self.service_id, self.values)

            time.sleep(1)  # Simulate some work being done
            print(f"\t - service_response: {service_response}")
            for label in service_response:
                self.update_output(label, service_response[label])

            output_data = {
                output.label: output
                for output in self.outputs
                if output.label is not None
            }

            self.last_execution = datetime.datetime.now()
            self.status = "completed"
            return output_data
        except Exception as e:
            print(f"Error executing node {self.service_type}:{self.node_id}: {e}")

    async def get_setup(self, setup_id: str) -> Dict[str, Any]:
        """
        Get the setup data for the given setup id.

        Args:
            setup_id (str): The unique identifier of the setup.

        Returns:
            Dict[str, Any]: The setup data.
        """
        return {
            "setup_id": setup_id,
            "setup_data": f"setup_data_{setup_id}",
        }

    def update_input(self, label: str, value: Any) -> None:
        for input in self.inputs:
            # print(f"\t\t- input: {input}, label: {label}")
            if input.label == label:
                input.value = value
                input.updated_at = datetime.datetime.now()
                break

    def update_output(self, label: str, value: Any) -> None:
        for output in self.outputs:
            # print(f"\t\t- outputs: {output}, label: {label}")
            if output.label == label:
                output.value = value
                output.updated_at = datetime.datetime.now()
                break
