# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/setup/v1/assistant.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/setup/v1/assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from digitalkin.setup.v1 import tool_pb2 as digitalkin_dot_setup_dot_v1_dot_tool__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#digitalkin/setup/v1/assistant.proto\x12\x13\x64igitalkin.setup.v1\x1a\x1e\x64igitalkin/setup/v1/tool.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xf5\x01\n\tAssistant\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x1b\n\x06system\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x06system\x12\x35\n\x05model\x18\x03 \x01(\x0e\x32\x1a.digitalkin.setup.v1.ModelB\x03\xe0\x41\x04R\x05model\x12%\n\x0btemperature\x18\x04 \x01(\x02\x42\x03\xe0\x41\x03R\x0btemperature\x12\x34\n\x05tools\x18\x05 \x03(\x0b\x32\x19.digitalkin.setup.v1.ToolB\x03\xe0\x41\x03R\x05tools\x12\"\n\nmax_tokens\x18\x06 \x01(\x05\x42\x03\xe0\x41\x03R\tmaxTokens\"E\n\x15ListAssistantsRequest\x12,\n\x0forganization_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x0eorganizationId\"]\n\x16ListAssistantsResponse\x12\x43\n\nassistants\x18\x01 \x03(\x0b\x32\x1e.digitalkin.setup.v1.AssistantB\x03\xe0\x41\x03R\nassistants*\xa7\x02\n\x05Model\x12\x11\n\rMODEL_UNKNOWN\x10\x00\x12\x1b\n\x17MODEL_CLAUDE_3_5_SONNET\x10\x01\x12\x18\n\x14MODEL_CLAUDE_3_HAIKU\x10\x02\x12\x17\n\x13MODEL_CLAUDE_3_OPUS\x10\x03\x12\x19\n\x15MODEL_CLAUDE_3_SONNET\x10\x04\x12\x1a\n\x16MODEL_GEMINI_1_5_FLASH\x10\x05\x12\x18\n\x14MODEL_GEMINI_1_5_PRO\x10\x06\x12\x17\n\x13MODEL_GPT_3_5_TURBO\x10\x07\x12\x0f\n\x0bMODEL_GPT_4\x10\x08\x12\x15\n\x11MODEL_GPT_4_TURBO\x10\t\x12\x11\n\rMODEL_GPT_4_O\x10\n\x12\x16\n\x12MODEL_GPT_4_O_MINI\x10\x0b\x42\x99\x01\n\x17\x63om.digitalkin.setup.v1B\x0e\x41ssistantProtoH\x02P\x01\xa2\x02\x03\x44SX\xaa\x02\x13\x44igitalkin.Setup.V1\xca\x02\x13\x44igitalkin\\Setup\\V1\xe2\x02\x1f\x44igitalkin\\Setup\\V1\\GPBMetadata\xea\x02\x15\x44igitalkin::Setup::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.setup.v1.assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.digitalkin.setup.v1B\016AssistantProtoH\002P\001\242\002\003DSX\252\002\023Digitalkin.Setup.V1\312\002\023Digitalkin\\Setup\\V1\342\002\037Digitalkin\\Setup\\V1\\GPBMetadata\352\002\025Digitalkin::Setup::V1'
  _globals['_ASSISTANT'].fields_by_name['id']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_ASSISTANT'].fields_by_name['system']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['system']._serialized_options = b'\340A\003'
  _globals['_ASSISTANT'].fields_by_name['model']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['model']._serialized_options = b'\340A\004'
  _globals['_ASSISTANT'].fields_by_name['temperature']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['temperature']._serialized_options = b'\340A\003'
  _globals['_ASSISTANT'].fields_by_name['tools']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['tools']._serialized_options = b'\340A\003'
  _globals['_ASSISTANT'].fields_by_name['max_tokens']._loaded_options = None
  _globals['_ASSISTANT'].fields_by_name['max_tokens']._serialized_options = b'\340A\003'
  _globals['_LISTASSISTANTSREQUEST'].fields_by_name['organization_id']._loaded_options = None
  _globals['_LISTASSISTANTSREQUEST'].fields_by_name['organization_id']._serialized_options = b'\340A\002'
  _globals['_LISTASSISTANTSRESPONSE'].fields_by_name['assistants']._loaded_options = None
  _globals['_LISTASSISTANTSRESPONSE'].fields_by_name['assistants']._serialized_options = b'\340A\003'
  _globals['_MODEL']._serialized_start=540
  _globals['_MODEL']._serialized_end=835
  _globals['_ASSISTANT']._serialized_start=126
  _globals['_ASSISTANT']._serialized_end=371
  _globals['_LISTASSISTANTSREQUEST']._serialized_start=373
  _globals['_LISTASSISTANTSREQUEST']._serialized_end=442
  _globals['_LISTASSISTANTSRESPONSE']._serialized_start=444
  _globals['_LISTASSISTANTSRESPONSE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
