# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from digitalkin.setup.v1 import assistant_pb2 as digitalkin_dot_setup_dot_v1_dot_assistant__pb2
from digitalkin.setup.v1 import setup_pb2 as digitalkin_dot_setup_dot_v1_dot_setup__pb2
from digitalkin.setup.v1 import tool_pb2 as digitalkin_dot_setup_dot_v1_dot_tool__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SetupServiceStub(object):
    """SetupService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSetups = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/GetSetups',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsRequest.SerializeToString,
                response_deserializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsResponse.FromString,
                _registered_method=True)
        self.ReadSetup = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/ReadSetup',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupRequest.SerializeToString,
                response_deserializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupResponse.FromString,
                _registered_method=True)
        self.UpdateSetup = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/UpdateSetup',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.UpdateSetupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListAssistants = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/ListAssistants',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsRequest.SerializeToString,
                response_deserializer=digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/ListTools',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CreateTool = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/CreateTool',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.CreateToolRequest.SerializeToString,
                response_deserializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.Tool.FromString,
                _registered_method=True)
        self.UpdateTool = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/UpdateTool',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.UpdateToolRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteTool = channel.unary_unary(
                '/digitalkin.setup.v1.SetupService/DeleteTool',
                request_serializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.DeleteToolRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SetupServiceServicer(object):
    """SetupService
    """

    def GetSetups(self, request, context):
        """GetSetups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSetup(self, request, context):
        """ReadSetup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSetup(self, request, context):
        """UpdateSetup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssistants(self, request, context):
        """ListAssistants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """ListTools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTool(self, request, context):
        """CreateTool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTool(self, request, context):
        """UpdateTool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTool(self, request, context):
        """DeleteTool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSetups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetups,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsRequest.FromString,
                    response_serializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsResponse.SerializeToString,
            ),
            'ReadSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSetup,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupRequest.FromString,
                    response_serializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupResponse.SerializeToString,
            ),
            'UpdateSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSetup,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_setup__pb2.UpdateSetupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListAssistants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssistants,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsRequest.FromString,
                    response_serializer=digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.ListToolsResponse.SerializeToString,
            ),
            'CreateTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTool,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.CreateToolRequest.FromString,
                    response_serializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.Tool.SerializeToString,
            ),
            'UpdateTool': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTool,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.UpdateToolRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTool,
                    request_deserializer=digitalkin_dot_setup_dot_v1_dot_tool__pb2.DeleteToolRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.setup.v1.SetupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('digitalkin.setup.v1.SetupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SetupService(object):
    """SetupService
    """

    @staticmethod
    def GetSetups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/GetSetups',
            digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsRequest.SerializeToString,
            digitalkin_dot_setup_dot_v1_dot_setup__pb2.GetSetupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/ReadSetup',
            digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupRequest.SerializeToString,
            digitalkin_dot_setup_dot_v1_dot_setup__pb2.ReadSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/UpdateSetup',
            digitalkin_dot_setup_dot_v1_dot_setup__pb2.UpdateSetupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAssistants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/ListAssistants',
            digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsRequest.SerializeToString,
            digitalkin_dot_setup_dot_v1_dot_assistant__pb2.ListAssistantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/ListTools',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            digitalkin_dot_setup_dot_v1_dot_tool__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/CreateTool',
            digitalkin_dot_setup_dot_v1_dot_tool__pb2.CreateToolRequest.SerializeToString,
            digitalkin_dot_setup_dot_v1_dot_tool__pb2.Tool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/UpdateTool',
            digitalkin_dot_setup_dot_v1_dot_tool__pb2.UpdateToolRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.setup.v1.SetupService/DeleteTool',
            digitalkin_dot_setup_dot_v1_dot_tool__pb2.DeleteToolRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
