# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/setup/v2/setup.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/setup/v2/setup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64igitalkin/setup/v2/setup.proto\x12\x13\x64igitalkin.setup.v2\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"~\n\x04\x44\x61ta\x12 \n\tmodule_id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x08moduleId\x12\x1c\n\x07node_id\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x06nodeId\x12\x36\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructB\x03\xe0\x41\x03R\x07\x63ontent\"\xad\x01\n\x05Setup\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x17\n\x04name\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x04name\x12\x1a\n\x06kin_id\x18\x03 \x01(\tB\x03\xe0\x41\x03R\x05kinId\x12-\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x19.digitalkin.setup.v2.DataR\x04\x64\x61ta\x12+\n\rcreation_date\x18\x05 \x01(\x05\x42\x06\xe0\x41\x05\xe0\x41\x03R\x0c\x63reationDate\"2\n\x10ReadSetupRequest\x12\x1e\n\x08setup_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x07setupId\"J\n\x11ReadSetupResponse\x12\x35\n\x05setup\x18\x01 \x01(\x0b\x32\x1a.digitalkin.setup.v2.SetupB\x03\xe0\x41\x03R\x05setup\"S\n\x13GetNodeSetupRequest\x12\x1e\n\x08setup_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x07setupId\x12\x1c\n\x07node_id\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x06nodeId\"J\n\x14GetNodeSetupResponse\x12\x32\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.digitalkin.setup.v2.DataB\x03\xe0\x41\x03R\x04\x64\x61taB\x95\x01\n\x17\x63om.digitalkin.setup.v2B\nSetupProtoH\x02P\x01\xa2\x02\x03\x44SX\xaa\x02\x13\x44igitalkin.Setup.V2\xca\x02\x13\x44igitalkin\\Setup\\V2\xe2\x02\x1f\x44igitalkin\\Setup\\V2\\GPBMetadata\xea\x02\x15\x44igitalkin::Setup::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.setup.v2.setup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.digitalkin.setup.v2B\nSetupProtoH\002P\001\242\002\003DSX\252\002\023Digitalkin.Setup.V2\312\002\023Digitalkin\\Setup\\V2\342\002\037Digitalkin\\Setup\\V2\\GPBMetadata\352\002\025Digitalkin::Setup::V2'
  _globals['_DATA'].fields_by_name['module_id']._loaded_options = None
  _globals['_DATA'].fields_by_name['module_id']._serialized_options = b'\340A\003'
  _globals['_DATA'].fields_by_name['node_id']._loaded_options = None
  _globals['_DATA'].fields_by_name['node_id']._serialized_options = b'\340A\003'
  _globals['_DATA'].fields_by_name['content']._loaded_options = None
  _globals['_DATA'].fields_by_name['content']._serialized_options = b'\340A\003'
  _globals['_SETUP'].fields_by_name['id']._loaded_options = None
  _globals['_SETUP'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_SETUP'].fields_by_name['name']._loaded_options = None
  _globals['_SETUP'].fields_by_name['name']._serialized_options = b'\340A\003'
  _globals['_SETUP'].fields_by_name['kin_id']._loaded_options = None
  _globals['_SETUP'].fields_by_name['kin_id']._serialized_options = b'\340A\003'
  _globals['_SETUP'].fields_by_name['creation_date']._loaded_options = None
  _globals['_SETUP'].fields_by_name['creation_date']._serialized_options = b'\340A\005\340A\003'
  _globals['_READSETUPREQUEST'].fields_by_name['setup_id']._loaded_options = None
  _globals['_READSETUPREQUEST'].fields_by_name['setup_id']._serialized_options = b'\340A\002'
  _globals['_READSETUPRESPONSE'].fields_by_name['setup']._loaded_options = None
  _globals['_READSETUPRESPONSE'].fields_by_name['setup']._serialized_options = b'\340A\003'
  _globals['_GETNODESETUPREQUEST'].fields_by_name['setup_id']._loaded_options = None
  _globals['_GETNODESETUPREQUEST'].fields_by_name['setup_id']._serialized_options = b'\340A\002'
  _globals['_GETNODESETUPREQUEST'].fields_by_name['node_id']._loaded_options = None
  _globals['_GETNODESETUPREQUEST'].fields_by_name['node_id']._serialized_options = b'\340A\002'
  _globals['_GETNODESETUPRESPONSE'].fields_by_name['data']._loaded_options = None
  _globals['_GETNODESETUPRESPONSE'].fields_by_name['data']._serialized_options = b'\340A\003'
  _globals['_DATA']._serialized_start=146
  _globals['_DATA']._serialized_end=272
  _globals['_SETUP']._serialized_start=275
  _globals['_SETUP']._serialized_end=448
  _globals['_READSETUPREQUEST']._serialized_start=450
  _globals['_READSETUPREQUEST']._serialized_end=500
  _globals['_READSETUPRESPONSE']._serialized_start=502
  _globals['_READSETUPRESPONSE']._serialized_end=576
  _globals['_GETNODESETUPREQUEST']._serialized_start=578
  _globals['_GETNODESETUPREQUEST']._serialized_end=661
  _globals['_GETNODESETUPRESPONSE']._serialized_start=663
  _globals['_GETNODESETUPRESPONSE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
