# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/service/v1/kin/kin_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from proto.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+digitalkin/service/v1/kin/kin_service.proto\x12\x19\x64igitalkin.service.v1.kin\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"\xa5\x01\n\x0fStartKinRequest\x12-\n\x05input\x18\x01 \x01(\x0b\x32\x17.google.protobuf.StructR\x05input\x12-\n\x05setup\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\x05setup\x12\x15\n\x06kin_id\x18\x03 \x01(\tR\x05kinId\x12\x1d\n\ntrigger_id\x18\x04 \x01(\tR\ttriggerId\"\'\n\x0eStopKinRequest\x12\x15\n\x06kin_id\x18\x01 \x01(\tR\x05kinId\",\n\x13GetKinStatusRequest\x12\x15\n\x06kin_id\x18\x01 \x01(\tR\x05kinId\"h\n\x0bKinResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x1a\n\x06kin_id\x18\x03 \x01(\tH\x00R\x05kinId\x88\x01\x01\x42\t\n\x07_kin_id\"\x82\x01\n\x11KinStatusResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12<\n\x06status\x18\x02 \x01(\x0e\x32$.digitalkin.service.v1.kin.KinStatusR\x06status\x12\x15\n\x06kin_id\x18\x03 \x01(\tR\x05kinId*j\n\tKinStatus\x12\x0c\n\x08STARTING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07\x45XPIRED\x10\x04\x12\x0b\n\x07SUCCESS\x10\x05\x12\x0b\n\x07STOPPED\x10\x06\x32\xbc\x02\n\nKinService\x12\x62\n\x08StartKin\x12*.digitalkin.service.v1.kin.StartKinRequest\x1a&.digitalkin.service.v1.kin.KinResponse(\x01\x30\x01\x12\\\n\x07StopKin\x12).digitalkin.service.v1.kin.StopKinRequest\x1a&.digitalkin.service.v1.kin.KinResponse\x12l\n\x0cGetKinStatus\x12..digitalkin.service.v1.kin.GetKinStatusRequest\x1a,.digitalkin.service.v1.kin.KinStatusResponseB\xba\x01\n\x1d\x63om.digitalkin.service.v1.kinB\x0fKinServiceProtoH\x02P\x01\xa2\x02\x04\x44SVK\xaa\x02\x19\x44igitalkin.Service.V1.Kin\xca\x02\x19\x44igitalkin\\Service\\V1\\Kin\xe2\x02%Digitalkin\\Service\\V1\\Kin\\GPBMetadata\xea\x02\x1c\x44igitalkin::Service::V1::Kinb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.service.v1.kin.kin_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.digitalkin.service.v1.kinB\017KinServiceProtoH\002P\001\242\002\004DSVK\252\002\031Digitalkin.Service.V1.Kin\312\002\031Digitalkin\\Service\\V1\\Kin\342\002%Digitalkin\\Service\\V1\\Kin\\GPBMetadata\352\002\034Digitalkin::Service::V1::Kin'
  _KINSTATUS._serialized_start=623
  _KINSTATUS._serialized_end=729
  _STARTKINREQUEST._serialized_start=130
  _STARTKINREQUEST._serialized_end=295
  _STOPKINREQUEST._serialized_start=297
  _STOPKINREQUEST._serialized_end=336
  _GETKINSTATUSREQUEST._serialized_start=338
  _GETKINSTATUSREQUEST._serialized_end=382
  _KINRESPONSE._serialized_start=384
  _KINRESPONSE._serialized_end=488
  _KINSTATUSRESPONSE._serialized_start=491
  _KINSTATUSRESPONSE._serialized_end=621
  _KINSERVICE._serialized_start=732
  _KINSERVICE._serialized_end=1048
# @@protoc_insertion_point(module_scope)
