# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.digitalkin.service.v1.kin import kin_service_pb2 as digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2


class KinServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartKin = channel.stream_stream(
                '/digitalkin.service.v1.kin.KinService/StartKin',
                request_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StartKinRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.FromString,
                )
        self.StopKin = channel.unary_unary(
                '/digitalkin.service.v1.kin.KinService/StopKin',
                request_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StopKinRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.FromString,
                )
        self.GetKinStatus = channel.unary_unary(
                '/digitalkin.service.v1.kin.KinService/GetKinStatus',
                request_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.GetKinStatusRequest.SerializeToString,
                response_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinStatusResponse.FromString,
                )


class KinServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartKin(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopKin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKinStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartKin': grpc.stream_stream_rpc_method_handler(
                    servicer.StartKin,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StartKinRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.SerializeToString,
            ),
            'StopKin': grpc.unary_unary_rpc_method_handler(
                    servicer.StopKin,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StopKinRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.SerializeToString,
            ),
            'GetKinStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKinStatus,
                    request_deserializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.GetKinStatusRequest.FromString,
                    response_serializer=digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.service.v1.kin.KinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KinService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartKin(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/digitalkin.service.v1.kin.KinService/StartKin',
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StartKinRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopKin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.kin.KinService/StopKin',
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.StopKinRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKinStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitalkin.service.v1.kin.KinService/GetKinStatus',
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.GetKinStatusRequest.SerializeToString,
            digitalkin_dot_service_dot_v1_dot_kin_dot_kin__service__pb2.KinStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
