# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/module_registry/v1/module_registry_service.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/module_registry/v1/module_registry_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from digitalkin.module_registry.v1 import action_pb2 as digitalkin_dot_module__registry_dot_v1_dot_action__pb2
from digitalkin.module_registry.v1 import monitoring_pb2 as digitalkin_dot_module__registry_dot_v1_dot_monitoring__pb2
from digitalkin.module_registry.v1 import registration_pb2 as digitalkin_dot_module__registry_dot_v1_dot_registration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;digitalkin/module_registry/v1/module_registry_service.proto\x12\x1d\x64igitalkin.module_registry.v1\x1a*digitalkin/module_registry/v1/action.proto\x1a.digitalkin/module_registry/v1/monitoring.proto\x1a\x30\x64igitalkin/module_registry/v1/registration.proto2\xfb\x04\n\x15ModuleRegistryService\x12s\n\x0eRegisterModule\x12..digitalkin.module_registry.v1.RegisterRequest\x1a/.digitalkin.module_registry.v1.RegisterResponse\"\x00\x12y\n\x10\x44\x65registerModule\x12\x30.digitalkin.module_registry.v1.DeregisterRequest\x1a\x31.digitalkin.module_registry.v1.DeregisterResponse\"\x00\x12s\n\x0e\x44iscoverModule\x12..digitalkin.module_registry.v1.DiscoverRequest\x1a/.digitalkin.module_registry.v1.DiscoverResponse\"\x00\x12\x7f\n\x12UpdateModuleStatus\x12\x32.digitalkin.module_registry.v1.UpdateStatusRequest\x1a\x33.digitalkin.module_registry.v1.UpdateStatusResponse\"\x00\x12|\n\rGetAllModules\x12\x33.digitalkin.module_registry.v1.GetAllModulesRequest\x1a\x34.digitalkin.module_registry.v1.GetAllModulesResponse\"\x00\x42\xd3\x01\n!com.digitalkin.module_registry.v1B\x1aModuleRegistryServiceProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x1c\x44igitalkin.ModuleRegistry.V1\xca\x02\x1c\x44igitalkin\\ModuleRegistry\\V1\xe2\x02(Digitalkin\\ModuleRegistry\\V1\\GPBMetadata\xea\x02\x1e\x44igitalkin::ModuleRegistry::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module_registry.v1.module_registry_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.digitalkin.module_registry.v1B\032ModuleRegistryServiceProtoH\002P\001\242\002\003DMX\252\002\034Digitalkin.ModuleRegistry.V1\312\002\034Digitalkin\\ModuleRegistry\\V1\342\002(Digitalkin\\ModuleRegistry\\V1\\GPBMetadata\352\002\036Digitalkin::ModuleRegistry::V1'
  _globals['_MODULEREGISTRYSERVICE']._serialized_start=237
  _globals['_MODULEREGISTRYSERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
