# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/module_registry/v1/registration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0digitalkin/module_registry/v1/registration.proto\x12\x1d\x64igitalkin.module_registry.v1\x1a\x17validate/validate.proto\"\xbd\x01\n\x0fRegisterRequest\x12$\n\tmodule_id\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x08moduleId\x12@\n\x0bmodule_type\x18\x02 \x01(\tB\x1f\xfa\x42\x1cr\x1aR\x07triggerR\x04toolR\x03kinR\x04viewR\nmoduleType\x12!\n\x07\x61\x64\x64ress\x18\x03 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x07\x61\x64\x64ress\x12\x1f\n\x04port\x18\x04 \x01(\x05\x42\x0b\xfa\x42\x08\x1a\x06\x18\xff\xff\x03(\x01R\x04port\",\n\x10RegisterResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"0\n\x11\x44\x65registerRequest\x12\x1b\n\tmodule_id\x18\x01 \x01(\tR\x08moduleId\".\n\x12\x44\x65registerResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07successB\xca\x01\n!com.digitalkin.module_registry.v1B\x11RegistrationProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x1c\x44igitalkin.ModuleRegistry.V1\xca\x02\x1c\x44igitalkin\\ModuleRegistry\\V1\xe2\x02(Digitalkin\\ModuleRegistry\\V1\\GPBMetadata\xea\x02\x1e\x44igitalkin::ModuleRegistry::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module_registry.v1.registration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.digitalkin.module_registry.v1B\021RegistrationProtoH\002P\001\242\002\003DMX\252\002\034Digitalkin.ModuleRegistry.V1\312\002\034Digitalkin\\ModuleRegistry\\V1\342\002(Digitalkin\\ModuleRegistry\\V1\\GPBMetadata\352\002\036Digitalkin::ModuleRegistry::V1'
  _REGISTERREQUEST.fields_by_name['module_id']._options = None
  _REGISTERREQUEST.fields_by_name['module_id']._serialized_options = b'\372B\004r\002\020\001'
  _REGISTERREQUEST.fields_by_name['module_type']._options = None
  _REGISTERREQUEST.fields_by_name['module_type']._serialized_options = b'\372B\034r\032R\007triggerR\004toolR\003kinR\004view'
  _REGISTERREQUEST.fields_by_name['address']._options = None
  _REGISTERREQUEST.fields_by_name['address']._serialized_options = b'\372B\004r\002\020\001'
  _REGISTERREQUEST.fields_by_name['port']._options = None
  _REGISTERREQUEST.fields_by_name['port']._serialized_options = b'\372B\010\032\006\030\377\377\003(\001'
  _REGISTERREQUEST._serialized_start=109
  _REGISTERREQUEST._serialized_end=298
  _REGISTERRESPONSE._serialized_start=300
  _REGISTERRESPONSE._serialized_end=344
  _DEREGISTERREQUEST._serialized_start=346
  _DEREGISTERREQUEST._serialized_end=394
  _DEREGISTERRESPONSE._serialized_start=396
  _DEREGISTERRESPONSE._serialized_end=442
# @@protoc_insertion_point(module_scope)
