# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/module/v1/information.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/module/v1/information.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&digitalkin/module/v1/information.proto\x12\x14\x64igitalkin.module.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"i\n\x15GetModuleInputRequest\x12\x31\n\tmodule_id\x18\x01 \x01(\tB\x14\xbaH\x11r\x0c\x10\x01:\x08modules:\xc8\x01\x01R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"j\n\x16GetModuleOutputRequest\x12\x31\n\tmodule_id\x18\x01 \x01(\tB\x14\xbaH\x11r\x0c\x10\x01:\x08modules:\xc8\x01\x01R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"i\n\x15GetModuleSetupRequest\x12\x31\n\tmodule_id\x18\x01 \x01(\tB\x14\xbaH\x11r\x0c\x10\x01:\x08modules:\xc8\x01\x01R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"v\n\x16GetModuleInputResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x42\n\x0cinput_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x06\xbaH\x03\xc8\x01\x01R\x0binputSchema\"y\n\x17GetModuleOutputResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x44\n\routput_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x06\xbaH\x03\xc8\x01\x01R\x0coutputSchema\"v\n\x16GetModuleSetupResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x42\n\x0csetup_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x06\xbaH\x03\xc8\x01\x01R\x0bsetupSchemaB\xa0\x01\n\x18\x63om.digitalkin.module.v1B\x10InformationProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x14\x44igitalkin.Module.V1\xca\x02\x14\x44igitalkin\\Module\\V1\xe2\x02 Digitalkin\\Module\\V1\\GPBMetadata\xea\x02\x16\x44igitalkin::Module::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module.v1.information_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.digitalkin.module.v1B\020InformationProtoH\002P\001\242\002\003DMX\252\002\024Digitalkin.Module.V1\312\002\024Digitalkin\\Module\\V1\342\002 Digitalkin\\Module\\V1\\GPBMetadata\352\002\026Digitalkin::Module::V1'
  _globals['_GETMODULEINPUTREQUEST'].fields_by_name['module_id']._loaded_options = None
  _globals['_GETMODULEINPUTREQUEST'].fields_by_name['module_id']._serialized_options = b'\272H\021r\014\020\001:\010modules:\310\001\001'
  _globals['_GETMODULEOUTPUTREQUEST'].fields_by_name['module_id']._loaded_options = None
  _globals['_GETMODULEOUTPUTREQUEST'].fields_by_name['module_id']._serialized_options = b'\272H\021r\014\020\001:\010modules:\310\001\001'
  _globals['_GETMODULESETUPREQUEST'].fields_by_name['module_id']._loaded_options = None
  _globals['_GETMODULESETUPREQUEST'].fields_by_name['module_id']._serialized_options = b'\272H\021r\014\020\001:\010modules:\310\001\001'
  _globals['_GETMODULEINPUTRESPONSE'].fields_by_name['input_schema']._loaded_options = None
  _globals['_GETMODULEINPUTRESPONSE'].fields_by_name['input_schema']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETMODULEOUTPUTRESPONSE'].fields_by_name['output_schema']._loaded_options = None
  _globals['_GETMODULEOUTPUTRESPONSE'].fields_by_name['output_schema']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETMODULESETUPRESPONSE'].fields_by_name['setup_schema']._loaded_options = None
  _globals['_GETMODULESETUPRESPONSE'].fields_by_name['setup_schema']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETMODULEINPUTREQUEST']._serialized_start=123
  _globals['_GETMODULEINPUTREQUEST']._serialized_end=228
  _globals['_GETMODULEOUTPUTREQUEST']._serialized_start=230
  _globals['_GETMODULEOUTPUTREQUEST']._serialized_end=336
  _globals['_GETMODULESETUPREQUEST']._serialized_start=338
  _globals['_GETMODULESETUPREQUEST']._serialized_end=443
  _globals['_GETMODULEINPUTRESPONSE']._serialized_start=445
  _globals['_GETMODULEINPUTRESPONSE']._serialized_end=563
  _globals['_GETMODULEOUTPUTRESPONSE']._serialized_start=565
  _globals['_GETMODULEOUTPUTRESPONSE']._serialized_end=686
  _globals['_GETMODULESETUPRESPONSE']._serialized_start=688
  _globals['_GETMODULESETUPRESPONSE']._serialized_end=806
# @@protoc_insertion_point(module_scope)
