# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/module/v1/information.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from proto.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&digitalkin/module/v1/information.proto\x12\x14\x64igitalkin.module.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"f\n\x15GetModuleInputRequest\x12.\n\tmodule_id\x18\x01 \x01(\tB\x11\xfa\x42\x0er\x0c\x10\x01:\x08modules:R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"g\n\x16GetModuleOutputRequest\x12.\n\tmodule_id\x18\x01 \x01(\tB\x11\xfa\x42\x0er\x0c\x10\x01:\x08modules:R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"f\n\x15GetModuleSetupRequest\x12.\n\tmodule_id\x18\x01 \x01(\tB\x11\xfa\x42\x0er\x0c\x10\x01:\x08modules:R\x08moduleId\x12\x1d\n\nllm_format\x18\x02 \x01(\x08R\tllmFormat\"x\n\x16GetModuleInputResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x44\n\x0cinput_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x0binputSchema\"{\n\x17GetModuleOutputResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x46\n\routput_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x0coutputSchema\"x\n\x16GetModuleSetupResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x44\n\x0csetup_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x0bsetupSchemaB\xa0\x01\n\x18\x63om.digitalkin.module.v1B\x10InformationProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x14\x44igitalkin.Module.V1\xca\x02\x14\x44igitalkin\\Module\\V1\xe2\x02 Digitalkin\\Module\\V1\\GPBMetadata\xea\x02\x16\x44igitalkin::Module::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module.v1.information_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.digitalkin.module.v1B\020InformationProtoH\002P\001\242\002\003DMX\252\002\024Digitalkin.Module.V1\312\002\024Digitalkin\\Module\\V1\342\002 Digitalkin\\Module\\V1\\GPBMetadata\352\002\026Digitalkin::Module::V1'
  _GETMODULEINPUTREQUEST.fields_by_name['module_id']._options = None
  _GETMODULEINPUTREQUEST.fields_by_name['module_id']._serialized_options = b'\372B\016r\014\020\001:\010modules:'
  _GETMODULEOUTPUTREQUEST.fields_by_name['module_id']._options = None
  _GETMODULEOUTPUTREQUEST.fields_by_name['module_id']._serialized_options = b'\372B\016r\014\020\001:\010modules:'
  _GETMODULESETUPREQUEST.fields_by_name['module_id']._options = None
  _GETMODULESETUPREQUEST.fields_by_name['module_id']._serialized_options = b'\372B\016r\014\020\001:\010modules:'
  _GETMODULEINPUTRESPONSE.fields_by_name['input_schema']._options = None
  _GETMODULEINPUTRESPONSE.fields_by_name['input_schema']._serialized_options = b'\372B\005\242\001\002\010\001'
  _GETMODULEOUTPUTRESPONSE.fields_by_name['output_schema']._options = None
  _GETMODULEOUTPUTRESPONSE.fields_by_name['output_schema']._serialized_options = b'\372B\005\242\001\002\010\001'
  _GETMODULESETUPRESPONSE.fields_by_name['setup_schema']._options = None
  _GETMODULESETUPRESPONSE.fields_by_name['setup_schema']._serialized_options = b'\372B\005\242\001\002\010\001'
  _GETMODULEINPUTREQUEST._serialized_start=119
  _GETMODULEINPUTREQUEST._serialized_end=221
  _GETMODULEOUTPUTREQUEST._serialized_start=223
  _GETMODULEOUTPUTREQUEST._serialized_end=326
  _GETMODULESETUPREQUEST._serialized_start=328
  _GETMODULESETUPREQUEST._serialized_end=430
  _GETMODULEINPUTRESPONSE._serialized_start=432
  _GETMODULEINPUTRESPONSE._serialized_end=552
  _GETMODULEOUTPUTRESPONSE._serialized_start=554
  _GETMODULEOUTPUTRESPONSE._serialized_end=677
  _GETMODULESETUPRESPONSE._serialized_start=679
  _GETMODULESETUPRESPONSE._serialized_end=799
# @@protoc_insertion_point(module_scope)
