# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/module/v1/module_service.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/module/v1/module_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from digitalkin.module.v1 import information_pb2 as digitalkin_dot_module_dot_v1_dot_information__pb2
from digitalkin.module.v1 import lifecycle_pb2 as digitalkin_dot_module_dot_v1_dot_lifecycle__pb2
from digitalkin.module.v1 import monitoring_pb2 as digitalkin_dot_module_dot_v1_dot_monitoring__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)digitalkin/module/v1/module_service.proto\x12\x14\x64igitalkin.module.v1\x1a&digitalkin/module/v1/information.proto\x1a$digitalkin/module/v1/lifecycle.proto\x1a%digitalkin/module/v1/monitoring.proto2\xfc\x05\n\rModuleService\x12\x66\n\x0bStartModule\x12(.digitalkin.module.v1.StartModuleRequest\x1a).digitalkin.module.v1.StartModuleResponse(\x01\x30\x01\x12_\n\nStopModule\x12\'.digitalkin.module.v1.StopModuleRequest\x1a(.digitalkin.module.v1.StopModuleResponse\x12n\n\x0fGetModuleStatus\x12,.digitalkin.module.v1.GetModuleStatusRequest\x1a-.digitalkin.module.v1.GetModuleStatusResponse\x12h\n\rGetModuleJobs\x12*.digitalkin.module.v1.GetModuleJobsRequest\x1a+.digitalkin.module.v1.GetModuleJobsResponse\x12k\n\x0eGetModuleInput\x12+.digitalkin.module.v1.GetModuleInputRequest\x1a,.digitalkin.module.v1.GetModuleInputResponse\x12n\n\x0fGetModuleOutput\x12,.digitalkin.module.v1.GetModuleOutputRequest\x1a-.digitalkin.module.v1.GetModuleOutputResponse\x12k\n\x0eGetModuleSetup\x12+.digitalkin.module.v1.GetModuleSetupRequest\x1a,.digitalkin.module.v1.GetModuleSetupResponseB\xa2\x01\n\x18\x63om.digitalkin.module.v1B\x12ModuleServiceProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x14\x44igitalkin.Module.V1\xca\x02\x14\x44igitalkin\\Module\\V1\xe2\x02 Digitalkin\\Module\\V1\\GPBMetadata\xea\x02\x16\x44igitalkin::Module::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module.v1.module_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.digitalkin.module.v1B\022ModuleServiceProtoH\002P\001\242\002\003DMX\252\002\024Digitalkin.Module.V1\312\002\024Digitalkin\\Module\\V1\342\002 Digitalkin\\Module\\V1\\GPBMetadata\352\002\026Digitalkin::Module::V1'
  _globals['_MODULESERVICE']._serialized_start=185
  _globals['_MODULESERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
