# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/module/v1/monitoring.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%digitalkin/module/v1/monitoring.proto\x12\x14\x64igitalkin.module.v1\x1a\x17validate/validate.proto\"?\n\x16GetModuleStatusRequest\x12%\n\x06job_id\x18\x01 \x01(\tB\x0e\xfa\x42\x0br\t\x10\x01:\x05jobs:R\x05jobId\"\xa0\x01\n\x17GetModuleStatusResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x44\n\x06status\x18\x02 \x01(\x0e\x32\".digitalkin.module.v1.ModuleStatusB\x08\xfa\x42\x05\x82\x01\x02\x10\x01R\x06status\x12%\n\x06job_id\x18\x03 \x01(\tB\x0e\xfa\x42\x0br\t\x10\x01:\x05jobs:R\x05jobId*\xea\x01\n\x0cModuleStatus\x12\x19\n\x15MODULE_STATUS_UNKNOWN\x10\x00\x12\x1a\n\x16MODULE_STATUS_STARTING\x10\x01\x12\x1c\n\x18MODULE_STATUS_PROCESSING\x10\x02\x12\x1a\n\x16MODULE_STATUS_CANCELED\x10\x03\x12\x18\n\x14MODULE_STATUS_FAILED\x10\x04\x12\x19\n\x15MODULE_STATUS_EXPIRED\x10\x05\x12\x19\n\x15MODULE_STATUS_SUCCESS\x10\x06\x12\x19\n\x15MODULE_STATUS_STOPPED\x10\x07\x42\x9f\x01\n\x18\x63om.digitalkin.module.v1B\x0fMonitoringProtoH\x02P\x01\xa2\x02\x03\x44MX\xaa\x02\x14\x44igitalkin.Module.V1\xca\x02\x14\x44igitalkin\\Module\\V1\xe2\x02 Digitalkin\\Module\\V1\\GPBMetadata\xea\x02\x16\x44igitalkin::Module::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.module.v1.monitoring_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.digitalkin.module.v1B\017MonitoringProtoH\002P\001\242\002\003DMX\252\002\024Digitalkin.Module.V1\312\002\024Digitalkin\\Module\\V1\342\002 Digitalkin\\Module\\V1\\GPBMetadata\352\002\026Digitalkin::Module::V1'
  _GETMODULESTATUSREQUEST.fields_by_name['job_id']._options = None
  _GETMODULESTATUSREQUEST.fields_by_name['job_id']._serialized_options = b'\372B\013r\t\020\001:\005jobs:'
  _GETMODULESTATUSRESPONSE.fields_by_name['status']._options = None
  _GETMODULESTATUSRESPONSE.fields_by_name['status']._serialized_options = b'\372B\005\202\001\002\020\001'
  _GETMODULESTATUSRESPONSE.fields_by_name['job_id']._options = None
  _GETMODULESTATUSRESPONSE.fields_by_name['job_id']._serialized_options = b'\372B\013r\t\020\001:\005jobs:'
  _MODULESTATUS._serialized_start=317
  _MODULESTATUS._serialized_end=551
  _GETMODULESTATUSREQUEST._serialized_start=88
  _GETMODULESTATUSREQUEST._serialized_end=151
  _GETMODULESTATUSRESPONSE._serialized_start=154
  _GETMODULESTATUSRESPONSE._serialized_end=314
# @@protoc_insertion_point(module_scope)
