# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitalkin/service/v1/tool/tool_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from proto.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-digitalkin/service/v1/tool/tool_service.proto\x12\x1a\x64igitalkin.service.v1.tool\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"\xf7\x01\n\x0e\x45xecuteRequest\x12\x37\n\x05input\x18\x01 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x05input\x12\x37\n\x05setup\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x05setup\x12)\n\x0bservice_ids\x18\x03 \x03(\tB\x08\xfa\x42\x05\x92\x01\x02\x08\x01R\nserviceIds\x12 \n\x07tool_id\x18\x04 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x06toolId\x12&\n\nmission_id\x18\x05 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\tmissionId\"f\n\x0f\x45xecuteResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x39\n\x06output\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x06output2w\n\x0bToolService\x12h\n\x0b\x45xecuteTool\x12*.digitalkin.service.v1.tool.ExecuteRequest\x1a+.digitalkin.service.v1.tool.ExecuteResponse(\x01\x42\xc0\x01\n\x1e\x63om.digitalkin.service.v1.toolB\x10ToolServiceProtoH\x02P\x01\xa2\x02\x04\x44SVT\xaa\x02\x1a\x44igitalkin.Service.V1.Tool\xca\x02\x1a\x44igitalkin\\Service\\V1\\Tool\xe2\x02&Digitalkin\\Service\\V1\\Tool\\GPBMetadata\xea\x02\x1d\x44igitalkin::Service::V1::Toolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.service.v1.tool.tool_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.digitalkin.service.v1.toolB\020ToolServiceProtoH\002P\001\242\002\004DSVT\252\002\032Digitalkin.Service.V1.Tool\312\002\032Digitalkin\\Service\\V1\\Tool\342\002&Digitalkin\\Service\\V1\\Tool\\GPBMetadata\352\002\035Digitalkin::Service::V1::Tool'
  _EXECUTEREQUEST.fields_by_name['input']._options = None
  _EXECUTEREQUEST.fields_by_name['input']._serialized_options = b'\372B\005\242\001\002\010\001'
  _EXECUTEREQUEST.fields_by_name['setup']._options = None
  _EXECUTEREQUEST.fields_by_name['setup']._serialized_options = b'\372B\005\242\001\002\010\001'
  _EXECUTEREQUEST.fields_by_name['service_ids']._options = None
  _EXECUTEREQUEST.fields_by_name['service_ids']._serialized_options = b'\372B\005\222\001\002\010\001'
  _EXECUTEREQUEST.fields_by_name['tool_id']._options = None
  _EXECUTEREQUEST.fields_by_name['tool_id']._serialized_options = b'\372B\004r\002\020\001'
  _EXECUTEREQUEST.fields_by_name['mission_id']._options = None
  _EXECUTEREQUEST.fields_by_name['mission_id']._serialized_options = b'\372B\004r\002\020\001'
  _EXECUTERESPONSE.fields_by_name['output']._options = None
  _EXECUTERESPONSE.fields_by_name['output']._serialized_options = b'\372B\005\242\001\002\010\001'
  _EXECUTEREQUEST._serialized_start=133
  _EXECUTEREQUEST._serialized_end=380
  _EXECUTERESPONSE._serialized_start=382
  _EXECUTERESPONSE._serialized_end=484
  _TOOLSERVICE._serialized_start=486
  _TOOLSERVICE._serialized_end=605
# @@protoc_insertion_point(module_scope)
