import datetime
import pickle
import threading
import time
from queue import Queue
from typing import Any, Dict, List
from concurrent.futures import ThreadPoolExecutor, as_completed

import matplotlib.pyplot as plt
import networkx as nx


# https://mermaid.live/edit#pako:eNqFVEty2kAQvUqXNtqYC7BIygZsbGNIlb2KyGKiaWBcUo88H1dStu-SLefgYukZGlASl8OK15_Xn9ejl6K2GothsXaq28DDeEnAv_Pq_NHGgA6a0mjQETqHrWFMFqOG3S9oFKxMg6BL_IF1DMbSt33yRfXFRgf1Rj1FlARmyBWGyUzrRIwc44MK0Se6skPShtYlYGCfByUNfFhqVD0oCpDqvBMEVKIP0CkPz0ZjYn6KpWnAsZkjuUrujos9Yw2RDv1os1rttg6ZmtPK2rZdgwF1KWXH1cS51L_ebQPWYbdF-Cy-SXUfbNehE3xZjSwFQ_FouapmCrq_e-WWBtiwMbd6YJtW4902xbrUPYtA2uH7okjGdTUrkTy231MBBM9TGupi8FCnRpAozRWJK6ksAiaUtyFxCnis3RZak6V5TGoeGrqpRkcBj-uKojISlC4SJR0l_raa5BH3Cf1GZz0mDyx2rn3gkqC7_5X7R5v56XSZ1se6Ru95zF7ehye1-EMveQ4wGHyCCznvDEZygBnIqxkn8LqI5hUmfcvc0itcyjnkhCu5hJN72rdkCqkwzQnXIu7JfdO3ZIqFKJQTbmX9Gcxk4xncyWYzmMvS-jMt9qA4K1p0rTKaPw8vybUswgZbXBZD_qtxpWITlsWS3jhUxWDvf1JdDIOLeFbETquAY6P42bcHo7NxvSmGK9V4Rp2ir9a2gt9-A4TCe7o


class Node:
    """
    Represents a node in the graph.

    Attributes:
        node_id (str): The unique identifier of the node.
        node_type (str): The type of the node.
        inputs (List[Dict[str, Any]]): The inputs of the node.
        outputs (List[Dict[str, Any]]): The outputs of the node.
        status (str): The status of the node execution.
        current_execution (int): The current execution count.
        last_execution (datetime.datetime): The timestamp of the last execution.
        lock (threading.Lock): A lock to ensure thread safety during execution.
    """

    def __init__(
        self,
        node_id: str,
        node_type: str,
        inputs: List[Dict[str, Any]],
        outputs: List[Dict[str, Any]],
    ):
        self.node_id = node_id
        self.node_type = node_type
        self.inputs = inputs
        self.outputs = outputs
        self.status = "pending"  # 'pending', 'running', 'completed', 'failed'
        self.current_execution = 0
        self.last_execution = datetime.datetime.now()
        self.lock = threading.Lock()

    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes the node with the given input data.

        Args:
            input_data (Dict[str, Any]): The input data for the node.

        Returns:
            Dict[str, Any]: The output data generated by the node.
        """
        with self.lock:
            self.status = "running"
            print(f"Executing node {self.node_id} of type {self.node_type}")
            time.sleep(5)  # Simulate some work being done
            output_data = {
                output["label"]: f"output_of_{output['label']}_{self.node_id}"
                for output in self.outputs
            }
            self.outputs = [
                {
                    **output,
                    "value": f"output_of_{output['label']}_{self.node_id}",
                    "updated_at": datetime.datetime.now(),
                }
                for output in self.outputs
            ]
            self.status = "completed"
            return output_data


class GraphExecutor:
    """
    Executes a directed graph of nodes.

    Attributes:
        graph (nx.DiGraph): The directed graph.
        nodes (Dict[str, Node]): The nodes in the graph.
        lock (threading.Lock): A lock to ensure thread safety.
        error_occurred (threading.Event): An event to signal if an error occurred.
        execution_queue (Queue): A queue to manage node execution order.
    """

    def __init__(self, graph: Dict[str, Any]):
        self.graph = nx.DiGraph()
        self.nodes = {
            node["id"]: Node(
                node_id=node["id"],
                node_type=node["type"],
                inputs=node["data"]["inputs"],
                outputs=node["data"]["outputs"],
            )
            for node in graph["nodes"]
        }
        self.add_edges(graph["edges"])
        self.error_occurred = threading.Event()
        self.execution_queue = Queue()
        self.lock = threading.Lock()

    def add_edges(self, edges: List[Dict[str, Any]]) -> None:
        """
        Adds edges to the graph.

        Args:
            edges (List[Dict[str, Any]]): The edges to add.
        """
        for edge in edges:
            source_handle = edge.get("sourceHandle", "").split(":::") + ["", ""]
            target_handle = edge.get("targetHandle", "").split(":::") + ["", ""]

            self.graph.add_edge(
                edge["source"],
                edge["target"],
                source_handle={
                    "type": source_handle[0],
                    "label": source_handle[1],
                },
                target_handle={
                    "type": target_handle[0],
                    "label": target_handle[1],
                },
            )

    def check_for_cycles(self) -> None:
        """
        Checks the graph for cycles and raises an exception if any are found.
        """
        try:
            cycles = list(nx.find_cycle(self.graph, orientation="original"))
            if cycles:
                raise nx.NetworkXUnfeasible("Graph contains a cycle")
        except nx.NetworkXNoCycle:
            pass

    def update_successor_inputs(
        self, successor_id: str, source_data: Dict[str, Any], edge_data: Dict[str, Any]
    ) -> None:
        """
        Updates the inputs of a successor node based on the output of a predecessor node.

        Args:
            successor_id (str): The ID of the successor node.
            source_data (Dict[str, Any]): The output data from the predecessor node.
            edge_data (Dict[str, Any]): The edge data connecting the nodes.
        """
        successor = self.nodes[successor_id]
        source_label = edge_data.get("source_handle", {}).get("label", None)
        target_label = edge_data.get("target_handle", {}).get("label", None)

        if source_label is None or target_label is None:
            return

        for label in source_data:
            if label == source_label:
                for input in successor.inputs:
                    if input["label"] == target_label:
                        input["value"] = source_data[label]
                        input["updated_at"] = datetime.datetime.now()
                break

    def execute_node(self, node_id: str) -> None:
        """
        Executes a single node and updates its successors.

        Args:
            node_id (str): The ID of the node to execute.
        """
        node = self.nodes[node_id]
        input_data = {
            input["label"]: {
                "value": input.get("value", None),
                "updated_at": input.get("updated_at", None),
                "optional": input.get("optional", False),
            }
            for input in node.inputs
        }
        print(
            f"{datetime.datetime.now()} - Executing node {node_id} with inputs: {input_data}"
        )

        verify_values = [
            (values["value"] is not None or values.get("optional", False))
            for values in input_data.values()
        ]
        verify_update = [
            values["updated_at"] is None or values["updated_at"] > node.last_execution
            for values in input_data.values()
        ]

        try:
            if not (all(verify_values) and any(verify_update)):
                print(
                    f"{datetime.datetime.now()} - Skipping node {node_id} due to input conditions."
                )
                return

            with self.lock:
                output_data = node.execute(input_data)

                for successor in self.graph.successors(node_id):
                    self.update_successor_inputs(
                        successor,
                        output_data,
                        self.graph.get_edge_data(node_id, successor),
                    )

                    successor_input_data = {
                        input["label"]: {
                            "value": input.get("value", None),
                            "updated_at": input.get("updated_at", None),
                            "optional": input.get("optional", False),
                        }
                        for input in self.nodes[successor].inputs
                    }

                    verify_successor_values = [
                        (values["value"] is not None or values.get("optional", False))
                        for values in successor_input_data.values()
                    ]
                    verify_successor_update = [
                        values["updated_at"] is None
                        or values["updated_at"] > node.last_execution
                        for values in successor_input_data.values()
                    ]
                    if not (all(verify_values) and any(verify_update)):
                        print(
                            f"{datetime.datetime.now()} - Skipping successor {successor} due to input conditions."
                        )
                        return

                    if all(verify_successor_values) and any(verify_successor_update):
                        self.execution_queue.put(successor)
                        print(
                            f"{datetime.datetime.now()} - Adding node {successor} to execution queue."
                        )

                self.nodes[node_id].last_execution = datetime.datetime.now()
        except Exception as e:
            print(f"{datetime.datetime.now()} - Error executing node {node_id}: {e}")
            self.error_occurred.set()

    def execute(self, initial_node: str = "n_1") -> None:
        """
        Executes the graph starting from the initial node.

        Args:
            initial_node (str): The ID of the initial node to start execution from.
        """
        self.check_for_cycles()
        self.execution_queue.put(initial_node)
        print(
            f"{datetime.datetime.now()} - Adding initial node {initial_node} to execution queue."
        )

        with ThreadPoolExecutor(max_workers=10) as executor:
            futures = {}
            while (
                not (
                    self.execution_queue.empty()
                    and not any(
                        self.nodes[node_id].status == "running"
                        for node_id in self.nodes
                    )
                )
                or futures
            ):
                if self.error_occurred.is_set():
                    break

                while not self.execution_queue.empty():
                    node_id = self.execution_queue.get()
                    print(
                        f"{datetime.datetime.now()} - Getting node {node_id} from execution queue."
                    )
                    if node_id is not None:
                        future = executor.submit(self.execute_node, node_id)
                        futures[future] = node_id
                    print(
                        f"{datetime.datetime.now()} - {node_id}",
                        [f"{nid}: {self.nodes[nid].status}" for nid in self.nodes],
                    )
                # Check completed futures
                for future in as_completed(futures):
                    node_id = futures.pop(future)
                    try:
                        future.result()
                    except Exception as e:
                        print(
                            f"{datetime.datetime.now()} - Error executing node {node_id}: {e}"
                        )
                        self.error_occurred.set()
                        break
                print()

        if self.error_occurred.is_set():
            print(f"{datetime.datetime.now()} - Execution stopped due to an error.")
        else:
            print(f"{datetime.datetime.now()} - Graph execution completed.")
            print(
                f"{datetime.datetime.now()} - queue empty {self.execution_queue.empty()}"
            )
            print(
                [f"{node_id}: {self.nodes[node_id].status}" for node_id in self.nodes]
            )

    def save_state(self, filename: str) -> None:
        """
        Saves the current state of the graph executor to a file.

        Args:
            filename (str): The name of the file to save the state to.
        """
        with open(filename, "wb") as f:
            pickle.dump(self, f)

    @staticmethod
    def load_state(filename: str) -> "GraphExecutor":
        """
        Loads the state of the graph executor from a file.

        Args:
            filename (str): The name of the file to load the state from.

        Returns:
            GraphExecutor: The loaded graph executor.
        """
        with open(filename, "rb") as f:
            return pickle.load(f)

    def visualize(self) -> None:
        """
        Visualizes the graph using matplotlib.
        """
        pos = nx.spring_layout(self.graph)
        color_map = {
            "pending": "gray",
            "running": "yellow",
            "completed": "green",
            "failed": "red",
        }
        fig, ax = plt.subplots()
        for node_id, (x, y) in pos.items():
            node = self.nodes[node_id]
            color = color_map[node.status]
            ax.add_patch(
                plt.Rectangle((x - 0.1, y - 0.05), 0.2, 0.1, color=color, ec="black")
            )
            ax.text(
                x,
                y,
                node_id,
                ha="center",
                va="center",
                color="white",
                fontsize=8,
                fontweight="bold",
            )
            input_text = "\n".join([f"IN: {inp['label']}" for inp in node.inputs])
            output_text = "\n".join([f"OUT: {out['label']}" for out in node.outputs])
            ax.text(
                x - 0.15,
                y,
                input_text,
                ha="right",
                va="center",
                color="black",
                fontsize=6,
            )
            ax.text(
                x + 0.15,
                y,
                output_text,
                ha="left",
                va="center",
                color="black",
                fontsize=6,
            )

        nx.draw_networkx_edges(self.graph, pos, ax=ax)
        plt.axis("off")
        plt.show()


# Example usage
if __name__ == "__main__":
    graph = {
        "edges": [
            {
                "source": "n_1",
                "sourceHandle": "text:::content",
                "target": "n_2",
                "targetHandle": "text:::FEC",
                "id": "xy-edge__n_1text:::content-n_2text:::FEC",
            },
            {
                "source": "n_2",
                "sourceHandle": "csv:::FEC",
                "target": "n_3",
                "targetHandle": "csv:::file",
                "id": "xy-edge__n_2csv:::FEC-n_3csv:::file",
            },
            {
                "source": "n_2",
                "sourceHandle": "text:::# facture manquante",
                "target": "n_4",
                "targetHandle": "text:::# facture",
                "id": "xy-edge__n_2text:::# facture manquante-n_4text:::# facture",
            },
        ],
        "nodes": [
            {
                "id": "n_1",
                "type": "wfbox",
                "data": {
                    "id": "1",
                    "name": "gmail",
                    "type": "trigger",
                    "color": "#686",
                    "inputs": [
                        {
                            "label": "smtp",
                            "type": "url",
                            "value": "google.com",
                            "updated_at": datetime.datetime.now(),
                        },
                        {
                            "label": "email",
                            "type": "email",
                            "value": "test@gmail.com",
                        },
                        {
                            "label": "password",
                            "type": "text",
                            "value": "1234",
                            "updated_at": datetime.datetime.now(),
                        },
                    ],
                    "outputs": [
                        {
                            "label": "from",
                            "type": "email",
                        },
                        {
                            "label": "content",
                            "type": "text",
                        },
                    ],
                },
            },
            {
                "id": "n_2",
                "type": "wfbox",
                "data": {
                    "id": "1",
                    "name": "comptable",
                    "type": "kin",
                    "inputs": [
                        {"label": "FEC", "type": "text"},
                        {"label": "facture", "type": "text", "optional": True},
                    ],
                    "outputs": [
                        {"label": "FEC", "type": "csv"},
                        {"label": "# facture manquante", "type": "text"},
                    ],
                },
            },
            {
                "id": "n_3",
                "type": "wfbox",
                "data": {
                    "id": "1",
                    "name": "csv",
                    "type": "view",
                    "inputs": [{"label": "file", "type": "csv"}],
                    "outputs": [],
                },
            },
            {
                "id": "n_4",
                "type": "wfbox",
                "data": {
                    "id": "1",
                    "name": "relance",
                    "type": "kin",
                    "inputs": [{"label": "# facture", "type": "text"}],
                    "outputs": [{"label": "facture", "type": "text"}],
                },
            },
        ],
    }

    executor = GraphExecutor(graph)
    executor.execute()
    # executor.visualize()
    # executor.save_state("graph_state.pkl")

    # To load the state and continue execution
    # executor = GraphExecutor.load_state('graph_state.pkl')
    # executor.execute()
    # executor.visualize()
