# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/activity.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$digitalkin/project/v1/activity.proto\x12\x15\x64igitalkin.project.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x03\n\x08\x41\x63tivity\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x1a\n\x06kin_id\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x05kinId\x12\x1b\n\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1e\n\x08kin_name\x18\x04 \x01(\tH\x01R\x07kinName\x88\x01\x01\x12(\n\rworkflow_name\x18\x05 \x01(\tH\x02R\x0cworkflowName\x88\x01\x01\x12\x1d\n\x07subject\x18\x06 \x01(\tB\x03\xe0\x41\x03R\x07subject\x12\x36\n\x04\x64\x61te\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xe0\x41\x05\xe0\x41\x03R\x04\x64\x61te\x12;\n\x08\x64uration\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x03R\x08\x64uration\x88\x01\x01\x12\x19\n\x05price\x18\t \x01(\x02H\x04R\x05price\x88\x01\x01\x42\t\n\x07_statusB\x0b\n\t_kin_nameB\x10\n\x0e_workflow_nameB\x0b\n\t_durationB\x08\n\x06_price\"C\n\x15ReadActivitiesRequest\x12\x1f\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02H\x00R\x05kinId\x88\x01\x01\x42\t\n\x07_kin_id\"R\n\nActivities\x12\x44\n\nactivities\x18\x01 \x03(\x0b\x32\x1f.digitalkin.project.v1.ActivityB\x03\xe0\x41\x03R\nactivitiesB\xa2\x01\n\x19\x63om.digitalkin.project.v1B\rActivityProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\rActivityProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_ACTIVITY'].fields_by_name['id']._loaded_options = None
  _globals['_ACTIVITY'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_ACTIVITY'].fields_by_name['kin_id']._loaded_options = None
  _globals['_ACTIVITY'].fields_by_name['kin_id']._serialized_options = b'\340A\003'
  _globals['_ACTIVITY'].fields_by_name['subject']._loaded_options = None
  _globals['_ACTIVITY'].fields_by_name['subject']._serialized_options = b'\340A\003'
  _globals['_ACTIVITY'].fields_by_name['date']._loaded_options = None
  _globals['_ACTIVITY'].fields_by_name['date']._serialized_options = b'\340A\005\340A\003'
  _globals['_READACTIVITIESREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_READACTIVITIESREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_ACTIVITIES'].fields_by_name['activities']._loaded_options = None
  _globals['_ACTIVITIES'].fields_by_name['activities']._serialized_options = b'\340A\003'
  _globals['_ACTIVITY']._serialized_start=130
  _globals['_ACTIVITY']._serialized_end=532
  _globals['_READACTIVITIESREQUEST']._serialized_start=534
  _globals['_READACTIVITIESREQUEST']._serialized_end=601
  _globals['_ACTIVITIES']._serialized_start=603
  _globals['_ACTIVITIES']._serialized_end=685
# @@protoc_insertion_point(module_scope)
