# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/edge.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n digitalkin/project/v1/edge.proto\x12\x15\x64igitalkin.project.v1\x1a\x1fgoogle/api/field_behavior.proto\"D\n\x08\x44\x61taEdge\x12\x19\n\x05\x63olor\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x05\x63olor\x12\x1d\n\x07running\x18\x02 \x01(\x08\x42\x03\xe0\x41\x03R\x07running\"\xa9\x02\n\x04\x45\x64ge\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x1b\n\x06source\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x06source\x12(\n\rsource_handle\x18\x03 \x01(\tH\x00R\x0csourceHandle\x88\x01\x01\x12\x1b\n\x06target\x18\x04 \x01(\tB\x03\xe0\x41\x03R\x06target\x12(\n\rtarget_handle\x18\x05 \x01(\tH\x01R\x0ctargetHandle\x88\x01\x01\x12\x17\n\x04type\x18\x06 \x01(\tH\x02R\x04type\x88\x01\x01\x12\x38\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x1f.digitalkin.project.v1.DataEdgeB\x03\xe0\x41\x03R\x04\x64\x61taB\x10\n\x0e_source_handleB\x10\n\x0e_target_handleB\x07\n\x05_type\"t\n\x16\x41\x64\x64\x45\x64geWorkflowRequest\x12$\n\x0bworkflow_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\nworkflowId\x12\x34\n\x04\x65\x64ge\x18\x02 \x01(\x0b\x32\x1b.digitalkin.project.v1.EdgeB\x03\xe0\x41\x02R\x04\x65\x64ge\"_\n\x19\x44\x65leteEdgeWorkflowRequest\x12$\n\x0bworkflow_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\nworkflowId\x12\x1c\n\x07\x65\x64ge_id\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x06\x65\x64geIdB\x9e\x01\n\x19\x63om.digitalkin.project.v1B\tEdgeProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\tEdgeProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_DATAEDGE'].fields_by_name['color']._loaded_options = None
  _globals['_DATAEDGE'].fields_by_name['color']._serialized_options = b'\340A\003'
  _globals['_DATAEDGE'].fields_by_name['running']._loaded_options = None
  _globals['_DATAEDGE'].fields_by_name['running']._serialized_options = b'\340A\003'
  _globals['_EDGE'].fields_by_name['id']._loaded_options = None
  _globals['_EDGE'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_EDGE'].fields_by_name['source']._loaded_options = None
  _globals['_EDGE'].fields_by_name['source']._serialized_options = b'\340A\003'
  _globals['_EDGE'].fields_by_name['target']._loaded_options = None
  _globals['_EDGE'].fields_by_name['target']._serialized_options = b'\340A\003'
  _globals['_EDGE'].fields_by_name['data']._loaded_options = None
  _globals['_EDGE'].fields_by_name['data']._serialized_options = b'\340A\003'
  _globals['_ADDEDGEWORKFLOWREQUEST'].fields_by_name['workflow_id']._loaded_options = None
  _globals['_ADDEDGEWORKFLOWREQUEST'].fields_by_name['workflow_id']._serialized_options = b'\340A\002'
  _globals['_ADDEDGEWORKFLOWREQUEST'].fields_by_name['edge']._loaded_options = None
  _globals['_ADDEDGEWORKFLOWREQUEST'].fields_by_name['edge']._serialized_options = b'\340A\002'
  _globals['_DELETEEDGEWORKFLOWREQUEST'].fields_by_name['workflow_id']._loaded_options = None
  _globals['_DELETEEDGEWORKFLOWREQUEST'].fields_by_name['workflow_id']._serialized_options = b'\340A\002'
  _globals['_DELETEEDGEWORKFLOWREQUEST'].fields_by_name['edge_id']._loaded_options = None
  _globals['_DELETEEDGEWORKFLOWREQUEST'].fields_by_name['edge_id']._serialized_options = b'\340A\002'
  _globals['_DATAEDGE']._serialized_start=92
  _globals['_DATAEDGE']._serialized_end=160
  _globals['_EDGE']._serialized_start=163
  _globals['_EDGE']._serialized_end=460
  _globals['_ADDEDGEWORKFLOWREQUEST']._serialized_start=462
  _globals['_ADDEDGEWORKFLOWREQUEST']._serialized_end=578
  _globals['_DELETEEDGEWORKFLOWREQUEST']._serialized_start=580
  _globals['_DELETEEDGEWORKFLOWREQUEST']._serialized_end=675
# @@protoc_insertion_point(module_scope)
