# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/kin.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/kin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.digitalkin.common.v1 import common_pb2 as digitalkin_dot_common_dot_v1_dot_common__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64igitalkin/project/v1/kin.proto\x12\x15\x64igitalkin.project.v1\x1a!digitalkin/common/v1/common.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xe7\x01\n\x03Kin\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x17\n\x04name\x18\x02 \x01(\tB\x03\xe0\x41\x03R\x04name\x12*\n\x0eorigin_address\x18\x03 \x01(\tB\x03\xe0\x41\x03R\roriginAddress\x12@\n\x07threads\x18\x04 \x03(\x0b\x32!.digitalkin.common.v1.ThreadReplyB\x03\xe0\x41\x03R\x07threads\x12\x44\n\x08workflow\x18\x05 \x01(\x0b\x32#.digitalkin.common.v1.WorkflowReplyB\x03\xe0\x41\x03R\x08workflow\",\n\x0eReadKinRequest\x12\x1a\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05kinId\"g\n\x1dUpdateKinOriginAddressRequest\x12\x1a\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05kinId\x12*\n\x0eorigin_address\x18\x02 \x01(\tB\x03\xe0\x41\x02R\roriginAddressB\x9d\x01\n\x19\x63om.digitalkin.project.v1B\x08KinProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.kin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\010KinProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_KIN'].fields_by_name['id']._loaded_options = None
  _globals['_KIN'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_KIN'].fields_by_name['name']._loaded_options = None
  _globals['_KIN'].fields_by_name['name']._serialized_options = b'\340A\003'
  _globals['_KIN'].fields_by_name['origin_address']._loaded_options = None
  _globals['_KIN'].fields_by_name['origin_address']._serialized_options = b'\340A\003'
  _globals['_KIN'].fields_by_name['threads']._loaded_options = None
  _globals['_KIN'].fields_by_name['threads']._serialized_options = b'\340A\003'
  _globals['_KIN'].fields_by_name['workflow']._loaded_options = None
  _globals['_KIN'].fields_by_name['workflow']._serialized_options = b'\340A\003'
  _globals['_READKINREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_READKINREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_UPDATEKINORIGINADDRESSREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_UPDATEKINORIGINADDRESSREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_UPDATEKINORIGINADDRESSREQUEST'].fields_by_name['origin_address']._loaded_options = None
  _globals['_UPDATEKINORIGINADDRESSREQUEST'].fields_by_name['origin_address']._serialized_options = b'\340A\002'
  _globals['_KIN']._serialized_start=127
  _globals['_KIN']._serialized_end=358
  _globals['_READKINREQUEST']._serialized_start=360
  _globals['_READKINREQUEST']._serialized_end=404
  _globals['_UPDATEKINORIGINADDRESSREQUEST']._serialized_start=406
  _globals['_UPDATEKINORIGINADDRESSREQUEST']._serialized_end=509
# @@protoc_insertion_point(module_scope)
