# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/message.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.digitalkin.common.v1 import common_pb2 as digitalkin_dot_common_dot_v1_dot_common__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#digitalkin/project/v1/message.proto\x12\x15\x64igitalkin.project.v1\x1a!digitalkin/common/v1/common.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xb6\x01\n\x0eMessageRequest\x12 \n\tthread_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x08threadId\x12,\n\x0forganization_id\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x0eorganizationId\x12\x1d\n\x07message\x18\x03 \x01(\tB\x03\xe0\x41\x02R\x07message\x12\x35\n\x05\x66iles\x18\x04 \x03(\x0b\x32\x1a.digitalkin.common.v1.FileB\x03\xe0\x41\x02R\x05\x66iles\"0\n\x0fMessageResponse\x12\x1d\n\x07\x63ontent\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x07\x63ontentB\xa1\x01\n\x19\x63om.digitalkin.project.v1B\x0cMessageProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\014MessageProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_MESSAGEREQUEST'].fields_by_name['thread_id']._loaded_options = None
  _globals['_MESSAGEREQUEST'].fields_by_name['thread_id']._serialized_options = b'\340A\002'
  _globals['_MESSAGEREQUEST'].fields_by_name['organization_id']._loaded_options = None
  _globals['_MESSAGEREQUEST'].fields_by_name['organization_id']._serialized_options = b'\340A\002'
  _globals['_MESSAGEREQUEST'].fields_by_name['message']._loaded_options = None
  _globals['_MESSAGEREQUEST'].fields_by_name['message']._serialized_options = b'\340A\002'
  _globals['_MESSAGEREQUEST'].fields_by_name['files']._loaded_options = None
  _globals['_MESSAGEREQUEST'].fields_by_name['files']._serialized_options = b'\340A\002'
  _globals['_MESSAGERESPONSE'].fields_by_name['content']._loaded_options = None
  _globals['_MESSAGERESPONSE'].fields_by_name['content']._serialized_options = b'\340A\003'
  _globals['_MESSAGEREQUEST']._serialized_start=131
  _globals['_MESSAGEREQUEST']._serialized_end=313
  _globals['_MESSAGERESPONSE']._serialized_start=315
  _globals['_MESSAGERESPONSE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
