# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/response.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$digitalkin/project/v1/response.proto\x12\x15\x64igitalkin.project.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n\x08Response\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x34\n\x04role\x18\x02 \x01(\x0e\x32\x1b.digitalkin.project.v1.RoleB\x03\xe0\x41\x04R\x04role\x12:\n\x06status\x18\x03 \x01(\x0e\x32\x1d.digitalkin.project.v1.StatusB\x03\xe0\x41\x04R\x06status\x12\x1d\n\x07\x63ontent\x18\x04 \x01(\tB\x03\xe0\x41\x03R\x07\x63ontent\x12\x43\n\x0b\x63reate_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xe0\x41\x05\xe0\x41\x03R\ncreateDate\x12 \n\torigin_id\x18\x06 \x01(\tB\x03\xe0\x41\x03R\x08originId*g\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_PENDING\x10\x01\x12\x0f\n\x0bSTATUS_DONE\x10\x02\x12\x10\n\x0cSTATUS_ERROR\x10\x03\x12\x12\n\x0eSTATUS_WAITING\x10\x04*;\n\x04Role\x12\x10\n\x0cROLE_UNKNOWN\x10\x00\x12\r\n\tROLE_USER\x10\x01\x12\x12\n\x0eROLE_ASSISTANT\x10\x02\x42\xa2\x01\n\x19\x63om.digitalkin.project.v1B\rResponseProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\rResponseProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_RESPONSE'].fields_by_name['id']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_RESPONSE'].fields_by_name['role']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['role']._serialized_options = b'\340A\004'
  _globals['_RESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['status']._serialized_options = b'\340A\004'
  _globals['_RESPONSE'].fields_by_name['content']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['content']._serialized_options = b'\340A\003'
  _globals['_RESPONSE'].fields_by_name['create_date']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['create_date']._serialized_options = b'\340A\005\340A\003'
  _globals['_RESPONSE'].fields_by_name['origin_id']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['origin_id']._serialized_options = b'\340A\003'
  _globals['_STATUS']._serialized_start=411
  _globals['_STATUS']._serialized_end=514
  _globals['_ROLE']._serialized_start=516
  _globals['_ROLE']._serialized_end=575
  _globals['_RESPONSE']._serialized_start=130
  _globals['_RESPONSE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
