# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/thread.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/thread.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.digitalkin.common.v1 import common_pb2 as digitalkin_dot_common_dot_v1_dot_common__pb2
from proto.digitalkin.project.v1 import response_pb2 as digitalkin_dot_project_dot_v1_dot_response__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"digitalkin/project/v1/thread.proto\x12\x15\x64igitalkin.project.v1\x1a!digitalkin/common/v1/common.proto\x1a$digitalkin/project/v1/response.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x8d\x01\n\x06Thread\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12*\n\x0ethread_subject\x18\x02 \x01(\tB\x03\xe0\x41\x03R\rthreadSubject\x12\x42\n\tresponses\x18\x03 \x03(\x0b\x32\x1f.digitalkin.project.v1.ResponseB\x03\xe0\x41\x03R\tresponses\"Q\n\x13\x43reateThreadRequest\x12\x1a\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05kinId\x12\x1e\n\x08setup_id\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x07setupId\"5\n\x11ReadThreadRequest\x12 \n\tthread_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x08threadId\"7\n\x13\x44\x65leteThreadRequest\x12 \n\tthread_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x08threadIdB\xa0\x01\n\x19\x63om.digitalkin.project.v1B\x0bThreadProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.thread_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\013ThreadProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_THREAD'].fields_by_name['id']._loaded_options = None
  _globals['_THREAD'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_THREAD'].fields_by_name['thread_subject']._loaded_options = None
  _globals['_THREAD'].fields_by_name['thread_subject']._serialized_options = b'\340A\003'
  _globals['_THREAD'].fields_by_name['responses']._loaded_options = None
  _globals['_THREAD'].fields_by_name['responses']._serialized_options = b'\340A\003'
  _globals['_CREATETHREADREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_CREATETHREADREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_CREATETHREADREQUEST'].fields_by_name['setup_id']._loaded_options = None
  _globals['_CREATETHREADREQUEST'].fields_by_name['setup_id']._serialized_options = b'\340A\002'
  _globals['_READTHREADREQUEST'].fields_by_name['thread_id']._loaded_options = None
  _globals['_READTHREADREQUEST'].fields_by_name['thread_id']._serialized_options = b'\340A\002'
  _globals['_DELETETHREADREQUEST'].fields_by_name['thread_id']._loaded_options = None
  _globals['_DELETETHREADREQUEST'].fields_by_name['thread_id']._serialized_options = b'\340A\002'
  _globals['_THREAD']._serialized_start=168
  _globals['_THREAD']._serialized_end=309
  _globals['_CREATETHREADREQUEST']._serialized_start=311
  _globals['_CREATETHREADREQUEST']._serialized_end=392
  _globals['_READTHREADREQUEST']._serialized_start=394
  _globals['_READTHREADREQUEST']._serialized_end=447
  _globals['_DELETETHREADREQUEST']._serialized_start=449
  _globals['_DELETETHREADREQUEST']._serialized_end=504
# @@protoc_insertion_point(module_scope)
