# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/project/v1/workflow.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/project/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.digitalkin.project.v1 import edge_pb2 as digitalkin_dot_project_dot_v1_dot_edge__pb2
from proto.digitalkin.project.v1 import node_pb2 as digitalkin_dot_project_dot_v1_dot_node__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$digitalkin/project/v1/workflow.proto\x12\x15\x64igitalkin.project.v1\x1a digitalkin/project/v1/edge.proto\x1a digitalkin/project/v1/node.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x8f\x01\n\x08Workflow\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x03R\x02id\x12\x36\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x1b.digitalkin.project.v1.EdgeB\x03\xe0\x41\x03R\x05\x65\x64ges\x12\x36\n\x05nodes\x18\x03 \x03(\x0b\x32\x1b.digitalkin.project.v1.NodeB\x03\xe0\x41\x03R\x05nodes\"\x87\x01\n\x15\x43reateWorkflowRequest\x12\x1a\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05kinId\x12\x45\n\x08workflow\x18\x02 \x01(\x0b\x32\x1f.digitalkin.project.v1.WorkflowB\x03\xe0\x41\x01H\x00R\x08workflow\x88\x01\x01\x42\x0b\n\t_workflow\"1\n\x13ReadWorkflowRequest\x12\x1a\n\x06kin_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05kinIdB\xa2\x01\n\x19\x63om.digitalkin.project.v1B\rWorkflowProtoH\x02P\x01\xa2\x02\x03\x44PX\xaa\x02\x15\x44igitalkin.Project.V1\xca\x02\x15\x44igitalkin\\Project\\V1\xe2\x02!Digitalkin\\Project\\V1\\GPBMetadata\xea\x02\x17\x44igitalkin::Project::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.project.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.digitalkin.project.v1B\rWorkflowProtoH\002P\001\242\002\003DPX\252\002\025Digitalkin.Project.V1\312\002\025Digitalkin\\Project\\V1\342\002!Digitalkin\\Project\\V1\\GPBMetadata\352\002\027Digitalkin::Project::V1'
  _globals['_WORKFLOW'].fields_by_name['id']._loaded_options = None
  _globals['_WORKFLOW'].fields_by_name['id']._serialized_options = b'\340A\003'
  _globals['_WORKFLOW'].fields_by_name['edges']._loaded_options = None
  _globals['_WORKFLOW'].fields_by_name['edges']._serialized_options = b'\340A\003'
  _globals['_WORKFLOW'].fields_by_name['nodes']._loaded_options = None
  _globals['_WORKFLOW'].fields_by_name['nodes']._serialized_options = b'\340A\003'
  _globals['_CREATEWORKFLOWREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_CREATEWORKFLOWREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_CREATEWORKFLOWREQUEST'].fields_by_name['workflow']._loaded_options = None
  _globals['_CREATEWORKFLOWREQUEST'].fields_by_name['workflow']._serialized_options = b'\340A\001'
  _globals['_READWORKFLOWREQUEST'].fields_by_name['kin_id']._loaded_options = None
  _globals['_READWORKFLOWREQUEST'].fields_by_name['kin_id']._serialized_options = b'\340A\002'
  _globals['_WORKFLOW']._serialized_start=165
  _globals['_WORKFLOW']._serialized_end=308
  _globals['_CREATEWORKFLOWREQUEST']._serialized_start=311
  _globals['_CREATEWORKFLOWREQUEST']._serialized_end=446
  _globals['_READWORKFLOWREQUEST']._serialized_start=448
  _globals['_READWORKFLOWREQUEST']._serialized_end=497
# @@protoc_insertion_point(module_scope)
