# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalkin/common/v1/common.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'digitalkin/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!digitalkin/common/v1/common.proto\x12\x14\x64igitalkin.common.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x05Thing\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n\x02tb\x18\x02 \x01(\tR\x02tb\"H\n\x04\x46ile\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n\x07\x63ontent\x18\x03 \x01(\x0cR\x07\x63ontent\"\xe7\x01\n\tUserReply\x12\x1b\n\tuser_name\x18\x01 \x01(\tR\x08userName\x12\"\n\nfirst_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n\tlast_name\x18\x03 \x01(\tH\x01R\x08lastName\x88\x01\x01\x12\x14\n\x05\x65mail\x18\x04 \x01(\tR\x05\x65mail\x12\x1b\n\x06\x61vatar\x18\x05 \x01(\tH\x02R\x06\x61vatar\x88\x01\x01\x12\x1c\n\tactivated\x18\x06 \x01(\x08R\tactivatedB\r\n\x0b_first_nameB\x0c\n\n_last_nameB\t\n\x07_avatar\"\x83\x01\n\x08KinReply\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12%\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x00R\x0b\x64\x65scription\x88\x01\x01\x12\x1c\n\tactivated\x18\x04 \x01(\x08R\tactivatedB\x0e\n\x0c_description\"b\n\x0bThreadReply\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12%\n\x0ethread_subject\x18\x02 \x01(\tR\rthreadSubject\x12\x1c\n\tactivated\x18\x03 \x01(\x08R\tactivated\"\xa1\x01\n\rWorkflowReply\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n\x06status\x18\x03 \x01(\tR\x06status\x12>\n\x08\x64uration\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xe0\x41\x05\xe0\x41\x03R\x08\x64uration\x12\x14\n\x05price\x18\x05 \x01(\x03R\x05priceB\x9b\x01\n\x18\x63om.digitalkin.common.v1B\x0b\x43ommonProtoH\x02P\x01\xa2\x02\x03\x44\x43X\xaa\x02\x14\x44igitalkin.Common.V1\xca\x02\x14\x44igitalkin\\Common\\V1\xe2\x02 Digitalkin\\Common\\V1\\GPBMetadata\xea\x02\x16\x44igitalkin::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalkin.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.digitalkin.common.v1B\013CommonProtoH\002P\001\242\002\003DCX\252\002\024Digitalkin.Common.V1\312\002\024Digitalkin\\Common\\V1\342\002 Digitalkin\\Common\\V1\\GPBMetadata\352\002\026Digitalkin::Common::V1'
  _globals['_WORKFLOWREPLY'].fields_by_name['duration']._loaded_options = None
  _globals['_WORKFLOWREPLY'].fields_by_name['duration']._serialized_options = b'\340A\005\340A\003'
  _globals['_THING']._serialized_start=125
  _globals['_THING']._serialized_end=164
  _globals['_FILE']._serialized_start=166
  _globals['_FILE']._serialized_end=238
  _globals['_USERREPLY']._serialized_start=241
  _globals['_USERREPLY']._serialized_end=472
  _globals['_KINREPLY']._serialized_start=475
  _globals['_KINREPLY']._serialized_end=606
  _globals['_THREADREPLY']._serialized_start=608
  _globals['_THREADREPLY']._serialized_end=706
  _globals['_WORKFLOWREPLY']._serialized_start=709
  _globals['_WORKFLOWREPLY']._serialized_end=870
# @@protoc_insertion_point(module_scope)
