"""TODO Sphinx docstring."""

import datetime
import time
from typing import Any, Dict, List, Callable, Optional

from pydantic import BaseModel, Field

from kin_sdk.common.types import ModuleType
from kin_sdk.exception import NodeExecutionException


class InputData(BaseModel):
    """TODO Sphinx docstring."""

    label: Optional[str] = Field(None, description="label of the input parameter")
    value: Optional[Any] = Field(None, description="value of the input parameter")
    updated_at: Optional[datetime.datetime] = Field(
        None, description="updated time of the input parameter or None if not updated"
    )
    optional: bool = Field(False, description="checking if the value is optional")


class OutputData(BaseModel):
    """TODO Sphinx docstring."""

    label: Optional[str] = Field(None, description="label of the output parameter")
    value: Optional[Any] = Field(None, description="value of the output parameter")
    updated_at: Optional[datetime.datetime] = Field(
        None, description="updated time of the output parameter or None if not updated"
    )
    optional: bool = Field(False, description="checking if the value is optional")


class Node:
    """
    Represents a node in the graph.

    Attributes:
        node_id (str): The unique identifier of the node.
        node_type (str): The type of the node.
        inputs (List[Dict[str, Any]]): The inputs of the node.
        outputs (List[Dict[str, Any]]): The outputs of the node.
        status (str): The status of the node execution.
        current_execution (int): The current execution count.
        last_execution (datetime.datetime): The timestamp of the last execution.
        lock (threading.Lock): A lock to ensure thread safety during execution.
    """

    def __init__(
        self,
        node_id: str,
        node_type: str,
        module_type: ModuleType,
        module_id: str,
        inputs: List[Dict[str, Any]],
        outputs: List[Dict[str, Any]],
        setup: Dict[str, Any],
    ):
        # value
        self.node_id = node_id
        self.node_type = node_type
        self.module_type = module_type
        self.module_id = module_id
        self.inputs = [InputData(**input) for input in inputs]
        self.outputs = [OutputData(**output) for output in outputs]
        self.status = "pending"  # 'pending', 'running', 'completed', 'failed'
        self.current_execution = 0
        self.last_execution = None
        self.setup = setup

    @property
    def values(self) -> Dict[str, Any]:
        """TODO Sphinx docstring."""
        inputs = {}
        for input_data in self.inputs:
            print(f"\t\t- input: {input_data}")
            if input_data.label is not None:
                inputs[input_data.label] = input_data.value
        return inputs

    async def execute(self, module_callback: Callable) -> Dict[str, OutputData]:
        """
        Executes the node with the given input data.

        Args:
            input_data (Dict[str, Any]): The input data for the node.

        Returns:
            Dict[str, Any]: The output data generated by the node.
        """
        try:
            self.status = "running"
            print(f"Executing node {self.module_type}:{self.node_id}")
            module_response = await module_callback(self.module_id, self.values)

            time.sleep(1)  # Simulate some work being done
            print(f"\t - module_response: {module_response}")
            for label in module_response:
                self.update_output(label, module_response[label])

            output_data = {
                output.label: output
                for output in self.outputs
                if output.label is not None
            }

            self.last_execution = datetime.datetime.now()
            self.status = "completed"
            return output_data
        except NodeExecutionException as e:
            print(f"Error executing node {self.module_type}:{self.node_id}: {e}")

    async def get_setup(self, setup_id: str) -> Dict[str, Any]:
        """
        Get the setup data for the given setup id.

        Args:
            setup_id (str): The unique identifier of the setup.

        Returns:
            Dict[str, Any]: The setup data.
        """
        return {
            "setup_id": setup_id,
            "setup_data": f"setup_data_{setup_id}",
        }

    def update_input(self, label: str, value: Any) -> None:
        """TODO Sphinx docstring."""
        for input_data in self.inputs:
            # print(f"\t\t- input: {input}, label: {label}")
            if input_data.label == label:
                input_data.value = value
                input_data.updated_at = datetime.datetime.now()
                break

    def update_output(self, label: str, value: Any) -> None:
        """TODO Sphinx docstring."""
        for output_data in self.outputs:
            # print(f"\t\t- outputs: {output}, label: {label}")
            if output_data.label == label:
                output_data.value = value
                output_data.updated_at = datetime.datetime.now()
                break
